# Nombre de la aplicación
spring.application.name=ud1-rest-lombok-h2

# ---------------------------------------------------------
# H2
# ---------------------------------------------------------

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:productosdb

# Usuario de H2
spring.datasource.username=sa

# Contraseña vacía
spring.datasource.password=

# Driver de H2
spring.datasource.driver-class-name=org.h2.Driver

# ---------------------------------------------------------
# JPA / Hibernate
# ---------------------------------------------------------

# Crea/actualiza las tablas a partir de las entidades
spring.jpa.hibernate.ddl-auto=create

# Muestra las consultas SQL en la consola
spring.jpa.show-sql=true

# Formatea el SQL para que sea más fácil de leer
spring.jpa.properties.hibernate.format_sql=true

# ---------------------------------------------------------
# Consola H2
# ---------------------------------------------------------

# Permite acceder a la consola web de H2
spring.h2.console.enabled=true

# Ruta de la consola
spring.h2.console.path=/h2-console
